// Velo page code for /register?e={e}  (custom element tag kb-register, element ID #kbPage)
// Paste into this page's code panel, replacing everything. Needs public/kb-velo.js and backend/events.jsw.
// Generated by pages/build.js: the collections listed here are the ones the page needs.
// Regular page; the event comes from the query string.
import { renderPage, sendResult } from 'public/kb-velo.js';
import wixLocationFrontend from 'wix-location-frontend';
import { registerForEvent } from 'backend/events.jsw';

const LABELS = { firstName: 'first name', lastName: 'last name', email: 'email', phone: 'phone', sessions: 'at least one session', experience: 'years refereeing', shirtSize: 'shirt fit and size' };

/** Backend answer -> what the element shows. */
function toResult(r) {
  if (r && r.ok) return { ok: true, ref: r.ref, updated: !!r.updated, status: r.status };
  const e = (r && r.error) || '';
  if (e === 'invalid') return { ok: false, fields: r.fields || [], message: 'Please check: ' + (r.fields || []).map((k) => LABELS[k] || k).join(', ') + '.' };
  if (e === 'closed') return { ok: false, message: 'Registration for this event is closed.' };
  if (e === 'notfound') return { ok: false, message: 'We couldn\u2019t find this event. Email admin@azref.com and we\u2019ll add you.' };
  return { ok: false };                         // the element shows its own "didn't go through" text
}

$w.onReady(async function () {
  const el = $w('#kbPage');
  el.on('kb-submit', async (event) => {
    const d = event.detail || {};
    let result;
    try { result = toResult(await registerForEvent(d.eventItemId, d.data, d.eventId)); }
    catch (err) { console.error('registerForEvent failed', err); result = { ok: false }; }
    sendResult(el, d.requestId, result);
  });
  const q = wixLocationFrontend.query || {};    // /register?e=<event id, e.g. academy-2026>
  await renderPage(el, 'kb-register', { eventId: q.e || 'academy-2026' });
});
