// Velo page code for /contact  (custom element tag kb-contact, element ID #kbPage)
// Paste into this page's code panel, replacing everything. Needs public/kb-velo.js and backend/contact.jsw.
// Generated by pages/build.js: the collections listed here are the ones the page needs.
import { renderPage, sendResult } from 'public/kb-velo.js';
import { sendContact } from 'backend/contact.jsw';

const LABELS = { name: 'name', email: 'email', role: 'I\'m a', topic: 'what it\'s about', message: 'message', parentEmail: 'parent or guardian email' };

/** Backend answer -> what the element shows. */
function toResult(r) {
  if (r && r.ok) return { ok: true, ref: r.ref };
  const e = (r && r.error) || '';
  if (e === 'invalid') return { ok: false, fields: r.fields || [], message: 'Please check: ' + (r.fields || []).map((k) => LABELS[k] || k).join(', ') + '.' };
  if (e === 'rate') return { ok: false, message: 'You\u2019ve sent several messages in the last hour. Please try again later, or email admin@azref.com.' };
  if (e === 'redirect') return { ok: false, fields: ['topic'], message: 'Please use the form above for this one, so it reaches the right people fast.' };
  return { ok: false };                         // the element shows its own "didn't go through" text + email fallback
}

$w.onReady(async function () {
  const el = $w('#kbPage');
  el.on('kb-submit', async (event) => {
    const d = event.detail || {};
    let result;
    try { result = toResult(await sendContact(d.data)); }
    catch (err) { console.error('sendContact failed', err); result = { ok: false }; }
    sendResult(el, d.requestId, result);
  });
  await renderPage(el, 'kb-contact');                // no CMS rows; passes ?topic= / ?q= to the page
});
