// Velo page code for /license?l={l}&t={t}  (custom element tag kb-license, element ID #kbPage)
// Paste into this page's code panel, replacing everything. Needs public/kb-velo.js.
// Generated by pages/build.js: the collections listed here are the ones the page needs.
// Regular page; the license comes from the query string.
import { renderPage } from 'public/kb-velo.js';
import wixLocationFrontend from 'wix-location-frontend';

$w.onReady(async function () {
  const q = wixLocationFrontend.query || {};    // /license?l=<licenseSlug>&t=<new|returning>
  if (!q.l) { wixLocationFrontend.to('/licenses'); return; }
  await renderPage($w('#kbPage'), 'kb-license', { slug: q.l || '', track: q.t || 'new' });
});
