// Velo page code for /  (custom element tag kb-home, element ID #kbPage)
// Paste into this page's code panel, replacing everything. Needs public/kb-velo.js.
// Generated by pages/build.js: the collections listed here are the ones the page needs.
import { renderPage } from 'public/kb-velo.js';

$w.onReady(async function () {
  await renderPage($w('#kbPage'), ['events', 'courses', 'fitness', 'announcements']);
});
